### PR TITLE
add onDonation fonction to call after the url opening

### PR DESCRIPTION
**Pull request by hatch01**
Hi, I added a voidCallback to call after launching the URL because I think it can be a very useful parameter.

### CODE REVIEW

**Review by Flajt — CHANGES_REQUESTED** [review]
Thanks for the PR. It's definitely a  nice feature to have.
There is one small spelling mistake: `///fonction to call after opening the url` to `///function [...]`, which needs to be fixed. 

I will merge this after the fix and try to get it shipped until next Monday.

**Comment by hatch01** [comment]
ok I fixed these small spelling mistake.

**Review by Flajt — APPROVED** [review]
Thanks a lot. I will merge it now.

**Comment by hatch01** [comment]
When will it be available on pub.dev ?

**Comment by Flajt** [comment]
I will push it over the weekend, latest on monday. For now, you should be able to use the updated version via referencing the following in the pubspec.yaml:  
```yaml
flutter_donation_buttons:
    git:
      url: git://github.com/Flajt/flutter_donation_buttons.git
      ref: main # branch name

```
[Here some more info](https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter#54023220)

**Comment by Flajt** [comment]
I just submitted it to pub.dev, after it's done with analyzing you should also be able to pull it from there. 
It should work (hopefully XD), I just updated the Readme, removed an icon package to improve package size, and added a runnable example app which should make further contributions easier.

**Comment by hatch01** [comment]
Thank you so much I will try it today

**Comment by hatch01** [comment]
Thank you so much I will try it today

**Pull request merged**
